version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    env_file: ./backend/env/backend.env
    volumes:
      - ./backend/src:/app/src
    depends_on:
      - sql_db

  sql_db:
    image: mysql
    restart: always
    env_file:
      - ./backend/env/database.env
    volumes:
      - database:/var/lib/mysql

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  database:
